apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: sse
  annotations:
    description: Template to build a sse container image to test applications on OCP.
    tags: java,sse
    iconClass: icon-rh-openjdk
    openshift.io/provider-display-name: Red Hat, Inc.
    openshift.io/support-url: https://access.redhat.com
labels:
  template: sse
objects:
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      labels:
        app: ${APPLICATION_NAME}
      name: ${APPLICATION_NAME}
      namespace: ${APP_NAMESPACE}
    spec:
      lookupPolicy:
        local: false
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      labels:
        app: ${APPLICATION_NAME}
      name: ${APPLICATION_NAME}
      namespace: ${APP_NAMESPACE}
    spec:
      nodeSelector:
      output:
        to:
          kind: ImageStreamTag
          name: ${APPLICATION_NAME}:v1
      postCommit: {}
      resources: {}
      runPolicy: Serial
      source:
        git:
          ref: main
          uri: https://github.com/ChrisPhillips-cminion/playingwithsse

      strategy:
        dockerStrategy:
          from:
            kind: ImageStreamTag
            name: python:latest
            namespace: openshift
        type: Dockerfile
      failedBuildsHistoryLimit: 2
      successfulBuildsHistoryLimit: 1
      triggers:
      - type: ConfigChange
      - type: ImageChange
parameters:
  - name: APPLICATION_NAME
    description: "The name of the Image stream (output)."
    required: false
    value: "sse"
  - name: APP_NAMESPACE
    description: "The namespace where the BuildConfig will be executed."
    required: true
